//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int ProductoId { get; set; }
        public string ProductoNombre { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        public Nullable<int> EnStock { get; set; }
        public Nullable<int> CategoriaId { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
