//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksClient.BooksService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://spring.io/guides/gs-producing-web-service", ConfigurationName="BooksService.LibrosPort")]
    public interface LibrosPort {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación deleteLibro no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BooksClient.BooksService.deleteLibroResponse1 deleteLibro(BooksClient.BooksService.deleteLibroRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BooksClient.BooksService.deleteLibroResponse1> deleteLibroAsync(BooksClient.BooksService.deleteLibroRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación getAllLibros no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BooksClient.BooksService.getAllLibrosResponse getAllLibros(BooksClient.BooksService.getAllLibrosRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BooksClient.BooksService.getAllLibrosResponse> getAllLibrosAsync(BooksClient.BooksService.getAllLibrosRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación getLibro no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BooksClient.BooksService.getLibroResponse1 getLibro(BooksClient.BooksService.getLibroRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BooksClient.BooksService.getLibroResponse1> getLibroAsync(BooksClient.BooksService.getLibroRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación createLibro no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BooksClient.BooksService.createLibroResponse1 createLibro(BooksClient.BooksService.createLibroRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BooksClient.BooksService.createLibroResponse1> createLibroAsync(BooksClient.BooksService.createLibroRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación updateLibro no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BooksClient.BooksService.updateLibroResponse1 updateLibro(BooksClient.BooksService.updateLibroRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BooksClient.BooksService.updateLibroResponse1> updateLibroAsync(BooksClient.BooksService.updateLibroRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spring.io/guides/gs-producing-web-service")]
    public partial class deleteLibroRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://spring.io/guides/gs-producing-web-service")]
    public partial class libro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string tituloField;
        
        private string autorField;
        
        private string editorialField;
        
        private long anoPublicacionField;
        
        private string isbnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("titulo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string autor {
            get {
                return this.autorField;
            }
            set {
                this.autorField = value;
                this.RaisePropertyChanged("autor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string editorial {
            get {
                return this.editorialField;
            }
            set {
                this.editorialField = value;
                this.RaisePropertyChanged("editorial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long anoPublicacion {
            get {
                return this.anoPublicacionField;
            }
            set {
                this.anoPublicacionField = value;
                this.RaisePropertyChanged("anoPublicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string isbn {
            get {
                return this.isbnField;
            }
            set {
                this.isbnField = value;
                this.RaisePropertyChanged("isbn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spring.io/guides/gs-producing-web-service")]
    public partial class deleteLibroResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteLibroRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spring.io/guides/gs-producing-web-service", Order=0)]
        public BooksClient.BooksService.deleteLibroRequest deleteLibroRequest;
        
        public deleteLibroRequest1() {
        }
        
        public deleteLibroRequest1(BooksClient.BooksService.deleteLibroRequest deleteLibroRequest) {
            this.deleteLibroRequest = deleteLibroRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteLibroResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spring.io/guides/gs-producing-web-service", Order=0)]
        public BooksClient.BooksService.deleteLibroResponse deleteLibroResponse;
        
        public deleteLibroResponse1() {
        }
        
        public deleteLibroResponse1(BooksClient.BooksService.deleteLibroResponse deleteLibroResponse) {
            this.deleteLibroResponse = deleteLibroResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spring.io/guides/gs-producing-web-service")]
    public partial class getAllLibrosRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllLibrosRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spring.io/guides/gs-producing-web-service", Order=0)]
        public BooksClient.BooksService.getAllLibrosRequest getAllLibrosRequest;
        
        public getAllLibrosRequest1() {
        }
        
        public getAllLibrosRequest1(BooksClient.BooksService.getAllLibrosRequest getAllLibrosRequest) {
            this.getAllLibrosRequest = getAllLibrosRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllLibrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllLibrosResponse", Namespace="http://spring.io/guides/gs-producing-web-service", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("libros", IsNullable=false)]
        public BooksClient.BooksService.libro[] getAllLibrosResponse1;
        
        public getAllLibrosResponse() {
        }
        
        public getAllLibrosResponse(BooksClient.BooksService.libro[] getAllLibrosResponse1) {
            this.getAllLibrosResponse1 = getAllLibrosResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spring.io/guides/gs-producing-web-service")]
    public partial class getLibroRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spring.io/guides/gs-producing-web-service")]
    public partial class getLibroResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private libro libroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public libro libro {
            get {
                return this.libroField;
            }
            set {
                this.libroField = value;
                this.RaisePropertyChanged("libro");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLibroRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spring.io/guides/gs-producing-web-service", Order=0)]
        public BooksClient.BooksService.getLibroRequest getLibroRequest;
        
        public getLibroRequest1() {
        }
        
        public getLibroRequest1(BooksClient.BooksService.getLibroRequest getLibroRequest) {
            this.getLibroRequest = getLibroRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLibroResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spring.io/guides/gs-producing-web-service", Order=0)]
        public BooksClient.BooksService.getLibroResponse getLibroResponse;
        
        public getLibroResponse1() {
        }
        
        public getLibroResponse1(BooksClient.BooksService.getLibroResponse getLibroResponse) {
            this.getLibroResponse = getLibroResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spring.io/guides/gs-producing-web-service")]
    public partial class createLibroRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private libro libroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public libro libro {
            get {
                return this.libroField;
            }
            set {
                this.libroField = value;
                this.RaisePropertyChanged("libro");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spring.io/guides/gs-producing-web-service")]
    public partial class createLibroResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createLibroRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spring.io/guides/gs-producing-web-service", Order=0)]
        public BooksClient.BooksService.createLibroRequest createLibroRequest;
        
        public createLibroRequest1() {
        }
        
        public createLibroRequest1(BooksClient.BooksService.createLibroRequest createLibroRequest) {
            this.createLibroRequest = createLibroRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createLibroResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spring.io/guides/gs-producing-web-service", Order=0)]
        public BooksClient.BooksService.createLibroResponse createLibroResponse;
        
        public createLibroResponse1() {
        }
        
        public createLibroResponse1(BooksClient.BooksService.createLibroResponse createLibroResponse) {
            this.createLibroResponse = createLibroResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spring.io/guides/gs-producing-web-service")]
    public partial class updateLibroRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private libro libroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public libro libro {
            get {
                return this.libroField;
            }
            set {
                this.libroField = value;
                this.RaisePropertyChanged("libro");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spring.io/guides/gs-producing-web-service")]
    public partial class updateLibroResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateLibroRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spring.io/guides/gs-producing-web-service", Order=0)]
        public BooksClient.BooksService.updateLibroRequest updateLibroRequest;
        
        public updateLibroRequest1() {
        }
        
        public updateLibroRequest1(BooksClient.BooksService.updateLibroRequest updateLibroRequest) {
            this.updateLibroRequest = updateLibroRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateLibroResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spring.io/guides/gs-producing-web-service", Order=0)]
        public BooksClient.BooksService.updateLibroResponse updateLibroResponse;
        
        public updateLibroResponse1() {
        }
        
        public updateLibroResponse1(BooksClient.BooksService.updateLibroResponse updateLibroResponse) {
            this.updateLibroResponse = updateLibroResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LibrosPortChannel : BooksClient.BooksService.LibrosPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LibrosPortClient : System.ServiceModel.ClientBase<BooksClient.BooksService.LibrosPort>, BooksClient.BooksService.LibrosPort {
        
        public LibrosPortClient() {
        }
        
        public LibrosPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LibrosPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibrosPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibrosPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BooksClient.BooksService.deleteLibroResponse1 BooksClient.BooksService.LibrosPort.deleteLibro(BooksClient.BooksService.deleteLibroRequest1 request) {
            return base.Channel.deleteLibro(request);
        }
        
        public BooksClient.BooksService.deleteLibroResponse deleteLibro(BooksClient.BooksService.deleteLibroRequest deleteLibroRequest) {
            BooksClient.BooksService.deleteLibroRequest1 inValue = new BooksClient.BooksService.deleteLibroRequest1();
            inValue.deleteLibroRequest = deleteLibroRequest;
            BooksClient.BooksService.deleteLibroResponse1 retVal = ((BooksClient.BooksService.LibrosPort)(this)).deleteLibro(inValue);
            return retVal.deleteLibroResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BooksClient.BooksService.deleteLibroResponse1> BooksClient.BooksService.LibrosPort.deleteLibroAsync(BooksClient.BooksService.deleteLibroRequest1 request) {
            return base.Channel.deleteLibroAsync(request);
        }
        
        public System.Threading.Tasks.Task<BooksClient.BooksService.deleteLibroResponse1> deleteLibroAsync(BooksClient.BooksService.deleteLibroRequest deleteLibroRequest) {
            BooksClient.BooksService.deleteLibroRequest1 inValue = new BooksClient.BooksService.deleteLibroRequest1();
            inValue.deleteLibroRequest = deleteLibroRequest;
            return ((BooksClient.BooksService.LibrosPort)(this)).deleteLibroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BooksClient.BooksService.getAllLibrosResponse BooksClient.BooksService.LibrosPort.getAllLibros(BooksClient.BooksService.getAllLibrosRequest1 request) {
            return base.Channel.getAllLibros(request);
        }
        
        public BooksClient.BooksService.libro[] getAllLibros(BooksClient.BooksService.getAllLibrosRequest getAllLibrosRequest) {
            BooksClient.BooksService.getAllLibrosRequest1 inValue = new BooksClient.BooksService.getAllLibrosRequest1();
            inValue.getAllLibrosRequest = getAllLibrosRequest;
            BooksClient.BooksService.getAllLibrosResponse retVal = ((BooksClient.BooksService.LibrosPort)(this)).getAllLibros(inValue);
            return retVal.getAllLibrosResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BooksClient.BooksService.getAllLibrosResponse> BooksClient.BooksService.LibrosPort.getAllLibrosAsync(BooksClient.BooksService.getAllLibrosRequest1 request) {
            return base.Channel.getAllLibrosAsync(request);
        }
        
        public System.Threading.Tasks.Task<BooksClient.BooksService.getAllLibrosResponse> getAllLibrosAsync(BooksClient.BooksService.getAllLibrosRequest getAllLibrosRequest) {
            BooksClient.BooksService.getAllLibrosRequest1 inValue = new BooksClient.BooksService.getAllLibrosRequest1();
            inValue.getAllLibrosRequest = getAllLibrosRequest;
            return ((BooksClient.BooksService.LibrosPort)(this)).getAllLibrosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BooksClient.BooksService.getLibroResponse1 BooksClient.BooksService.LibrosPort.getLibro(BooksClient.BooksService.getLibroRequest1 request) {
            return base.Channel.getLibro(request);
        }
        
        public BooksClient.BooksService.getLibroResponse getLibro(BooksClient.BooksService.getLibroRequest getLibroRequest) {
            BooksClient.BooksService.getLibroRequest1 inValue = new BooksClient.BooksService.getLibroRequest1();
            inValue.getLibroRequest = getLibroRequest;
            BooksClient.BooksService.getLibroResponse1 retVal = ((BooksClient.BooksService.LibrosPort)(this)).getLibro(inValue);
            return retVal.getLibroResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BooksClient.BooksService.getLibroResponse1> BooksClient.BooksService.LibrosPort.getLibroAsync(BooksClient.BooksService.getLibroRequest1 request) {
            return base.Channel.getLibroAsync(request);
        }
        
        public System.Threading.Tasks.Task<BooksClient.BooksService.getLibroResponse1> getLibroAsync(BooksClient.BooksService.getLibroRequest getLibroRequest) {
            BooksClient.BooksService.getLibroRequest1 inValue = new BooksClient.BooksService.getLibroRequest1();
            inValue.getLibroRequest = getLibroRequest;
            return ((BooksClient.BooksService.LibrosPort)(this)).getLibroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BooksClient.BooksService.createLibroResponse1 BooksClient.BooksService.LibrosPort.createLibro(BooksClient.BooksService.createLibroRequest1 request) {
            return base.Channel.createLibro(request);
        }
        
        public BooksClient.BooksService.createLibroResponse createLibro(BooksClient.BooksService.createLibroRequest createLibroRequest) {
            BooksClient.BooksService.createLibroRequest1 inValue = new BooksClient.BooksService.createLibroRequest1();
            inValue.createLibroRequest = createLibroRequest;
            BooksClient.BooksService.createLibroResponse1 retVal = ((BooksClient.BooksService.LibrosPort)(this)).createLibro(inValue);
            return retVal.createLibroResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BooksClient.BooksService.createLibroResponse1> BooksClient.BooksService.LibrosPort.createLibroAsync(BooksClient.BooksService.createLibroRequest1 request) {
            return base.Channel.createLibroAsync(request);
        }
        
        public System.Threading.Tasks.Task<BooksClient.BooksService.createLibroResponse1> createLibroAsync(BooksClient.BooksService.createLibroRequest createLibroRequest) {
            BooksClient.BooksService.createLibroRequest1 inValue = new BooksClient.BooksService.createLibroRequest1();
            inValue.createLibroRequest = createLibroRequest;
            return ((BooksClient.BooksService.LibrosPort)(this)).createLibroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BooksClient.BooksService.updateLibroResponse1 BooksClient.BooksService.LibrosPort.updateLibro(BooksClient.BooksService.updateLibroRequest1 request) {
            return base.Channel.updateLibro(request);
        }
        
        public BooksClient.BooksService.updateLibroResponse updateLibro(BooksClient.BooksService.updateLibroRequest updateLibroRequest) {
            BooksClient.BooksService.updateLibroRequest1 inValue = new BooksClient.BooksService.updateLibroRequest1();
            inValue.updateLibroRequest = updateLibroRequest;
            BooksClient.BooksService.updateLibroResponse1 retVal = ((BooksClient.BooksService.LibrosPort)(this)).updateLibro(inValue);
            return retVal.updateLibroResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BooksClient.BooksService.updateLibroResponse1> BooksClient.BooksService.LibrosPort.updateLibroAsync(BooksClient.BooksService.updateLibroRequest1 request) {
            return base.Channel.updateLibroAsync(request);
        }
        
        public System.Threading.Tasks.Task<BooksClient.BooksService.updateLibroResponse1> updateLibroAsync(BooksClient.BooksService.updateLibroRequest updateLibroRequest) {
            BooksClient.BooksService.updateLibroRequest1 inValue = new BooksClient.BooksService.updateLibroRequest1();
            inValue.updateLibroRequest = updateLibroRequest;
            return ((BooksClient.BooksService.LibrosPort)(this)).updateLibroAsync(inValue);
        }
    }
}
